# Generated by Django 4.1.1 on 2022-10-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_watchlist_listings_watchlist_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Miscellaneous', 'Miscellaneous'), ('Kitchen', 'Kitchen'), ('None', 'None')], default='None', max_length=64),
        ),
    ]
