# Generated by Django 4.1.1 on 2022-10-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Kitchen', 'Kitchen'), ('Pets', 'Pets'), ('Sport', 'Sport'), ('Fashion', 'Fashion'), ('Others', 'Others')], default='Sport', max_length=64),
        ),
    ]
